CREATE TABLE IF NOT EXISTS STUDENT (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    CONSTRAINT unique_email UNIQUE (email)
);